FROM  golang:1.21-alpine as builder

WORKDIR /app
COPY ./go.mod ./go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o main ./main.go

FROM  gcr.io/distroless/base-debian10

WORKDIR /app

COPY --from=builder /app/main /

EXPOSE 8080

CMD ["/main"]
